#!/system/bin/sh
exec 2>&1
n=0
setprop 'persist.pvr.2dtovr.button_back' '1' && n=$((n+1))
setprop 'persist.pvr.adb.root' '1' && n=$((n+1))
setprop 'persist.pvr.bcl.mode' '0' && n=$((n+1))
setprop 'persist.pvr.charge.policy' '3' && n=$((n+1))
setprop 'persist.pvr.config.enable_stencil_mesh' '0' && n=$((n+1))
setprop 'persist.pvr.config.eyebuffer_height' '1664' && n=$((n+1))
setprop 'persist.pvr.config.eyebuffer_width' '1664' && n=$((n+1))
setprop 'persist.pvr.config.target_fps' '-1' && n=$((n+1))
setprop 'persist.pvr.controller.index' '-1' && n=$((n+1))
setprop 'persist.pvr.current.countrycode' 'US' && n=$((n+1))
setprop 'persist.pvr.dashboard.enable' '1' && n=$((n+1))
setprop 'persist.pvr.debug.appfps' '0' && n=$((n+1))
setprop 'persist.pvr.debug.sysstatus' '0' && n=$((n+1))
setprop 'persist.pvr.default.home' 'com.picovrtob.vrlauncher' && n=$((n+1))
setprop 'persist.pvr.display.eb_enable' '1' && n=$((n+1))
setprop 'persist.pvr.display.eb_mode' '1' && n=$((n+1))
setprop 'persist.pvr.display.eb_use' '1' && n=$((n+1))
setprop 'persist.pvr.geomagnetic.mode' '0' && n=$((n+1))
setprop 'persist.pvr.global_6dof' 'true' && n=$((n+1))
setprop 'persist.pvr.isLog2SDCard' '1' && n=$((n+1))
setprop 'persist.pvr.loadanim' '1' && n=$((n+1))
setprop 'persist.pvr.logcatch' '0' && n=$((n+1))
setprop 'persist.pvr.mono.castmode' '1' && n=$((n+1))
setprop 'persist.pvr.mulkey.enable' '1' && n=$((n+1))
setprop 'persist.pvr.openrecenter' '0' && n=$((n+1))
setprop 'persist.pvr.otgmode' '0' && n=$((n+1))
setprop 'persist.pvr.outproxy.enable' 'true' && n=$((n+1))
setprop 'persist.pvr.performance_mode' '1' && n=$((n+1))
setprop 'persist.pvr.prebootmode' '0' && n=$((n+1))
setprop 'persist.pvr.psensor.reset_pose' '0' && n=$((n+1))
setprop 'persist.pvr.psensor_checkmode' '1' && n=$((n+1))
setprop 'persist.pvr.raycast.enable' '0' && n=$((n+1))
setprop 'persist.pvr.reset_mode' '0' && n=$((n+1))
setprop 'persist.pvr.screenoff.delay' '10' && n=$((n+1))
setprop 'persist.pvr.sdk.trackingmode' '4' && n=$((n+1))
setprop 'persist.pvr.sensor.source' '1' && n=$((n+1))
setprop 'persist.pvr.showsafety.tip' '1' && n=$((n+1))
setprop 'persist.pvr.sleep_by_static' '0' && n=$((n+1))
setprop 'persist.pvr.sleepmode' '2' && n=$((n+1))
setprop 'persist.pvr.surface.rotation' '1' && n=$((n+1))
setprop 'persist.pvr.volumeui' '1' && n=$((n+1))
setprop 'persist.pvr.vrtoast.enable' '1' && n=$((n+1))
setprop 'persist.pvr.wfd.enable' '1' && n=$((n+1))
setprop 'persist.pvr.wifi.autojoin' '0' && n=$((n+1))
setprop 'persist.pvrcon.6dof.backup' '110' && n=$((n+1))
setprop 'persist.pvrcon.config.status' '1' && n=$((n+1))
setprop 'persist.pvrcon.config.visible' '0' && n=$((n+1))
setprop 'persist.pvrcon.main.controller' '1' && n=$((n+1))
setprop 'persist.pvrcon.seethrough.enable' '1' && n=$((n+1))
setprop 'persist.pvrconfig.lens_ca_correction' '1' && n=$((n+1))
setprop 'persist.pvrpermission.autogrant' '0' && n=$((n+1))
setprop 'persist.pvrservice.eyetracking_autorun' '1' && n=$((n+1))
setprop 'persist.pvrservice.lens.fov' '101' && n=$((n+1))
setprop 'persist.pvrservice.trackingmode' '3' && n=$((n+1))
setprop 'persist.pxr.enablenoti' '0' && n=$((n+1))
setprop 'persist.pxr.eyetracking.fps' '90' && n=$((n+1))
echo "set $n properties"
echo "--- verify a few ---"
for k in persist.pvr.global_6dof persist.pvr.sdk.trackingmode persist.pvr.sensor.source persist.pvr.surface.rotation persist.pvr.config.eyebuffer_width; do
  echo "  $k = $(getprop $k)"
done
