#!/bin/bash
# Reproducible build of the in-process OpenXR runtime (libopenxr_monado.so)
# with the hsvr driver kit.
#
# Clones upstream Monado at a pinned commit, applies the hsvr registration
# patch, drops in the kit plus every driver under drivers/<name>/monado/,
# and builds for Android aarch64.
#
# Output: build-android/src/xrt/targets/openxr/libopenxr_monado.so
#
# Requires: Android NDK r27+, cmake, ninja, a local Eigen3 checkout
# (EIGEN3_ROOT or ../eigen relative to this script).

set -e
cd "$(dirname "$0")"
ROOT="$(pwd -P)"

MONADO_REPO="https://gitlab.freedesktop.org/monado/monado.git"
MONADO_COMMIT="09741cbcb45236f4f4f79790ea133cd90d68d5eb"

ANDROID_HOME="${ANDROID_HOME:-$HOME/Android/sdk}"
for root in "$ANDROID_HOME" "$HOME/Android/sdk" /opt/android-sdk; do
    [ -d "$root/ndk" ] || continue
    for ndk in "$root"/ndk/27.* "$root"/ndk/26.*; do
        [ -d "$ndk" ] && NDK="$ndk" && break 2
    done
done
: "${NDK:?no Android NDK 26/27 found}"

# Eigen is headers-only for Monado; fetch it and emit a minimal package config.
EIGEN3_ROOT="${EIGEN3_ROOT:-$(pwd)/../eigen-5.0.0}"
EIGEN_CFG="$(pwd)/../eigen-cmake"
if [ ! -d "$EIGEN3_ROOT/Eigen" ]; then
    echo "fetching eigen3 headers"
    mkdir -p "$EIGEN3_ROOT"
    curl -sL https://gitlab.com/libeigen/eigen/-/archive/5.0.0/eigen-5.0.0.tar.gz \
        | tar xz -C "$EIGEN3_ROOT" --strip-components=1
fi
mkdir -p "$EIGEN_CFG"
cat > "$EIGEN_CFG/Eigen3Config.cmake" <<EOF
if(NOT TARGET Eigen3::Eigen)
  add_library(Eigen3::Eigen INTERFACE IMPORTED)
  set_target_properties(Eigen3::Eigen PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "$EIGEN3_ROOT")
endif()
set(Eigen3_FOUND TRUE)
set(EIGEN3_FOUND TRUE)
set(Eigen3_VERSION "5.0.0")
set(EIGEN3_VERSION_STRING "5.0.0")
set(EIGEN3_VERSION_MAJOR 5)
set(EIGEN3_VERSION_MINOR 0)
set(EIGEN3_VERSION_PATCH 0)
set(EIGEN3_INCLUDE_DIRS "$EIGEN3_ROOT")
EOF

WORK=_monado-src
if [ ! -d "$WORK/.git" ]; then
    echo "cloning monado"
    git clone --filter=blob:none "$MONADO_REPO" "$WORK"
fi
cd "$WORK"
git fetch -q origin "$MONADO_COMMIT" 2>/dev/null || true
git checkout -q "$MONADO_COMMIT"

echo "applying hsvr patch + kit drivers"
git checkout -q . # drop local edits so the patch applies cleanly
git apply "$ROOT/patches/hsvr-driver-registration.patch"
git apply "$ROOT/patches/hsvr-compositor-pacing.patch"

# drv_hsvr builds from one directory: the kit, the hsvr prober shim, every
# device driver under drivers/<name>/monado/ and every shared controller
# under controllers/<name>/monado/, all flattened in.
# File names are prefixed <dev>_ by convention so devices cannot collide.
# wipe first: sources are globbed, so copies left from an earlier build
# (renamed/deleted drivers) would silently compile back in
HSVR_DST=src/xrt/drivers/hsvr
rm -rf "$HSVR_DST"
mkdir -p "$HSVR_DST"
cp "$ROOT"/../kit/hsvr_kit.c "$ROOT"/../kit/hsvr_kit.h "$HSVR_DST/"
cp "$ROOT"/driver/hsvr/*.c "$ROOT"/driver/hsvr/*.h "$HSVR_DST/"

# monorepo checkout keeps drivers/ at the root; a standalone hsvr/
# checkout under $PN2_ROOT finds it copied next to the build root
if [ -n "${HSVR_DRIVERS_DIR:-}" ]; then
    DRIVERS_DIR="$HSVR_DRIVERS_DIR"
elif [ -d "$ROOT/../../../drivers" ]; then
    DRIVERS_DIR="$ROOT/../../../drivers"
else
    DRIVERS_DIR="${PN2_ROOT:-$ROOT/../..}/drivers"
fi
DRV_NAMES=""
for d in "$DRIVERS_DIR"/*/monado; do
    [ -d "$d" ] || continue
    name=$(basename "$(dirname "$d")")
    cp "$d"/*.c "$d"/*.h "$HSVR_DST/"
    # shared wire-protocol headers (drivers/<name>/proto/*.h) ride along
    pd="$(dirname "$d")/proto"
    [ -d "$pd" ] && cp "$pd"/*.h "$HSVR_DST/"
    DRV_NAMES="$DRV_NAMES $name"
done

# headset-independent controllers live in their own tree so they never
# read as part of one headset: controllers/<name>/monado/ flattens into
# drv_hsvr exactly like a driver does
if [ -n "${HSVR_CONTROLLERS_DIR:-}" ]; then
    CONTROLLERS_DIR="$HSVR_CONTROLLERS_DIR"
elif [ -d "$ROOT/../../../controllers" ]; then
    CONTROLLERS_DIR="$ROOT/../../../controllers"
else
    CONTROLLERS_DIR="${PN2_ROOT:-$ROOT/../..}/controllers"
fi
CTRL_NAMES=""
for d in "$CONTROLLERS_DIR"/*/monado; do
    [ -d "$d" ] || continue
    name=$(basename "$(dirname "$d")")
    cp "$d"/*.c "$d"/*.h "$HSVR_DST/"
    pd="$(dirname "$d")/proto"
    [ -d "$pd" ] && cp "$pd"/*.h "$HSVR_DST/"
    CTRL_NAMES="$CTRL_NAMES $name"
done

# the kit resolves drivers by name at runtime; this table is what the
# registry iterates. Regenerated every build so adding drivers/<name>/
# is the only step a new device needs.
{
    echo '/* generated by build.sh - one extern per linked kit driver */'
    echo '#include "hsvr_kit.h"'
    for n in $DRV_NAMES; do
        echo "extern const struct hsvr_driver hsvr_drv_$n;"
    done
    echo 'const struct hsvr_driver *const hsvr_drivers[] = {'
    for n in $DRV_NAMES; do
        echo "    &hsvr_drv_$n,"
    done
    echo '    NULL,'
    echo '};'
} > "$HSVR_DST/hsvr_drivers.c"
echo "  kit drivers:$DRV_NAMES"

# same table for the generic controllers; always emitted so the kit
# links even on trees with no controllers/ checkout
{
    echo '/* generated by build.sh - one extern per linked kit controller */'
    echo '#include "hsvr_kit.h"'
    for n in $CTRL_NAMES; do
        echo "extern const struct hsvr_controller hsvr_ctrl_$n;"
    done
    echo 'const struct hsvr_controller *const hsvr_controllers[] = {'
    for n in $CTRL_NAMES; do
        echo "    &hsvr_ctrl_$n,"
    done
    echo '    NULL,'
    echo '};'
} > "$HSVR_DST/hsvr_controllers.c"
echo "  kit controllers:$CTRL_NAMES"

# the controller sharemem decoder is shared with the vrhome dash - one
# implementation, copied in at build time so there is no duplicated layout
CTRL_STATE_SRC="${PN2_VRHOME:-$ROOT/../../vrhome}/src/input"
# monorepo checkout: applications/vrhome sits three levels above monado/
if [ ! -f "$CTRL_STATE_SRC/ctrl_state.c" ]; then
    ALT="$ROOT/../../../applications/vrhome/src/input"
    [ -f "$ALT/ctrl_state.c" ] && CTRL_STATE_SRC="$ALT"
fi
for f in ctrl_state.c ctrl_state.h; do
    if [ ! -f "$CTRL_STATE_SRC/$f" ]; then
        echo "missing shared decoder $CTRL_STATE_SRC/$f (set PN2_VRHOME)" >&2
        exit 1
    fi
    cp "$CTRL_STATE_SRC/$f" "$HSVR_DST/"
done
cd ..

mkdir -p "$ROOT/build-android"
cd "$ROOT/build-android"
cmake -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE="$NDK/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-26 \
    -DANDROID_STL=c++_static \
    -DXRT_FEATURE_AHARDWARE_BUFFER=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DXRT_HAVE_WAYLAND=OFF -DXRT_HAVE_XLIB=OFF -DXRT_HAVE_XCB=OFF \
    -DXRT_FEATURE_SERVICE=OFF -DXRT_FEATURE_SERVICE_SYSTEMD=OFF \
    -DXRT_FEATURE_STEAMVR_PLUGIN=OFF \
    -DEigen3_DIR="$EIGEN_CFG" \
    "$ROOT/$WORK"
ninja openxr_monado

echo "built: $(pwd)/src/xrt/targets/openxr/libopenxr_monado.so"
