#include "ctrl_render.h"

#include "mesh.h"
#include "shape.h"
#include "../common/props.h"
#include "../hud/engine.h"
#include "../input/input_state.h"

#include <cstring>

// generated by tools/obj2c.py from models/*.obj
#include "ctrl_l.inc"
#include "ctrl_r.inc"

// the models are authored in arbitrary units around an off-origin pivot:
// fit them to a plausible handpiece size first, then the aim props swing
// the whole thing about the grip point
constexpr float kCtrlSize = 0.14f;

// build the pos+col VBO once per hand; aCol is flat since the mesh carries
// no materials of its own
static GLuint meshVbo(const unsigned char* obj, size_t len, int* verts) {
    Mesh m;
    if (!meshFromObj((const char*)obj, len, &m)) return 0;
    meshFit(&m, kCtrlSize);
    std::vector<float> buf(m.v.size() * 2);
    const float col[3] = {0.75f, 0.76f, 0.80f};
    for (size_t i = 0; i < m.v.size(); i += 3) {
        memcpy(&buf[i * 2], &m.v[i], 12);
        memcpy(&buf[i * 2 + 3], col, 12);
    }
    GLuint vbo = 0;
    glGenBuffers(1, &vbo);
    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, buf.size() * 4, buf.data(),
                 GL_STATIC_DRAW);
    *verts = (int)(m.v.size() / 3);
    return vbo;
}

void drawControllers(HudEngine* e, const Mat4& viewProj) {
    if (!e->ctrlVbo[0])
        e->ctrlVbo[0] = meshVbo(kObjL, kObjL_len, &e->ctrlVerts[0]);
    if (!e->ctrlVbo[1])
        e->ctrlVbo[1] = meshVbo(kObjR, kObjR_len, &e->ctrlVerts[1]);
    if (!e->ctrlVbo[0] && !e->ctrlVbo[1]) return;

    // orientation correction while the mount axes get settled on-device
    const float fx = propF("debug.vrhome.ctrlrx", 0.0f);
    const float fy = propF("debug.vrhome.ctrlry", 0.0f);
    const float fz = propF("debug.vrhome.ctrlrz", 0.0f);

    glUseProgram(e->sceneProg);
    const GLint aPos = glGetAttribLocation(e->sceneProg, "aPos");
    const GLint aCol = glGetAttribLocation(e->sceneProg, "aCol");
    const GLint uMVP = glGetUniformLocation(e->sceneProg, "uMVP");
    glEnableVertexAttribArray(aPos);
    glEnableVertexAttribArray(aCol);
    glEnable(GL_DEPTH_TEST);

    for (int w = 0; w < CTRL_COUNT; ++w) {
        if (!ctrlConnected(e->input, w) || !e->ctrlVbo[w]) continue;

        Mat4 model = multiply(e->ctrlMat[w],
                              multiply(rotY(fy), multiply(rotX(fx), rotZ(fz))));
        model.m[12] = e->ctrlPos[w][0];
        model.m[13] = e->ctrlPos[w][1];
        model.m[14] = e->ctrlPos[w][2];
        const Mat4 mvp = multiply(viewProj, model);
        glUniformMatrix4fv(uMVP, 1, GL_FALSE, mvp.m);
        glBindBuffer(GL_ARRAY_BUFFER, e->ctrlVbo[w]);
        glVertexAttribPointer(aPos, 3, GL_FLOAT, GL_FALSE, 24, nullptr);
        glVertexAttribPointer(aCol, 3, GL_FLOAT, GL_FALSE, 24,
                              (const void*)12);
        glDrawArrays(GL_TRIANGLES, 0, e->ctrlVerts[w]);
    }

    // the pointer beam: a camera-facing ribbon from the active controller
    // out to whatever it hit, or a fixed length into open space
    if (e->input.active >= 0) {
        const int w = e->input.active;
        const float* o = e->ctrlPos[w];
        const float* d = e->ctrlDir[w];
        const float len = e->aimHitT > 0.0f ? e->aimHitT : 4.0f;
        const float tip[3] = {o[0] + d[0] * len, o[1] + d[1] * len,
                              o[2] + d[2] * len};
        // widen toward the eye so the beam has a face from any angle
        float side[3] = {d[1] * (e->eyePos[2] - o[2]) -
                         d[2] * (e->eyePos[1] - o[1]),
                         d[2] * (e->eyePos[0] - o[0]) -
                         d[0] * (e->eyePos[2] - o[2]),
                         d[0] * (e->eyePos[1] - o[1]) -
                         d[1] * (e->eyePos[0] - o[0])};
        const float sm = sqrtf(side[0]*side[0] + side[1]*side[1] +
                               side[2]*side[2]);
        if (sm > 1e-6f) {
            const float hw = 0.0018f / sm;
            const float col[3] = {0.35f, 0.65f, 1.0f};
            float quad[36];
            const float* ends[2] = {o, tip};
            for (int c = 0; c < 2; ++c)
                for (int s2 = 0; s2 < 2; ++s2) {
                    const int v = (c * 2 + s2) * 6;
                    for (int a = 0; a < 3; ++a)
                        quad[v + a] = ends[c][a] +
                                      side[a] * hw * (s2 ? 1 : -1);
                    memcpy(&quad[v + 3], col, 12);
                }
            // two triangles: 0,1,2 / 2,1,3
            const int ord[6] = {0, 1, 2, 2, 1, 3};
            float tris[36];
            for (int i = 0; i < 6; ++i)
                memcpy(&tris[i * 6], &quad[ord[i] * 6], 24);

            const Mat4 mvp = multiply(viewProj, identity());
            glUniformMatrix4fv(uMVP, 1, GL_FALSE, mvp.m);
            glDisable(GL_DEPTH_TEST);
            glEnable(GL_BLEND);
            glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
            if (!e->ctrlBeamVbo) glGenBuffers(1, &e->ctrlBeamVbo);
            glBindBuffer(GL_ARRAY_BUFFER, e->ctrlBeamVbo);
            glBufferData(GL_ARRAY_BUFFER, sizeof(tris), tris,
                         GL_DYNAMIC_DRAW);
            glVertexAttribPointer(aPos, 3, GL_FLOAT, GL_FALSE, 24, nullptr);
            glVertexAttribPointer(aCol, 3, GL_FLOAT, GL_FALSE, 24,
                                  (const void*)12);
            glDrawArrays(GL_TRIANGLES, 0, 6);
            glDisable(GL_BLEND);
            glEnable(GL_DEPTH_TEST);
        }
    }

    glDisableVertexAttribArray(aPos);
    glDisableVertexAttribArray(aCol);
}
