#!/bin/bash
# Generate proprietary-files.txt from the actual extracted vendor tree rather
# than by hand. Groups by subsystem so the list stays reviewable.
set -u
V=/home/justin/pn2/vendor
OUT=/mnt/f/PN2Lineage/android/device/pico/A7B10/proprietary-files.txt
N=/mnt/f/PN2Lineage/notes/20_proprietary.log
mkdir -p "$(dirname "$OUT")"
exec 2>"$N"

emit() {  # header  find-args...
  echo ""
  echo "# $1"
  shift
  find "$V" "$@" -type f 2>/dev/null \
    | sed "s|^$V/|vendor/|" \
    | sort
}

{
cat <<'HDR'
# Proprietary blobs for the Pico Neo 2 (A7B10)
#
# Extracted from stock PUI 4.1.3 (b346). Nothing in this list is redistributed
# by this tree - extract-files.sh pulls them from the user's own device or from
# an official Pico OTA zip that the user downloads themselves.
#
# Generated by tools/20_gen_proprietary.sh against the real vendor partition.
HDR

emit "VR runtime - Qualcomm QVR framework" \( -name 'libqvr*' -o -name 'qvr*' -o -name 'libvraudio*' \)
emit "VR runtime - Pico (pxr/pvr)" \( -name '*pxr*' -o -name 'libpvr*' -o -path '*/etc/pvr/*' \)
emit "NDI electromagnetic controller tracking (FPGA + SLPI)" \( -name '*ndifpga*' -o -name 'sensors-common-*' -o -name 'sensors-icmxx*' -o -name 'sensors-light*' \)
emit "QVR configuration" -path '*/etc/qvr/*'
emit "Camera - tracking (ov9282) and eye (ov6211)" \( -path '*/lib*/camera/*' -o -name 'libqvrcamera*' \)
emit "Snapdragon Computer Vision Engine (SCVE) + FastCV" \( -name 'libscve*' -o -name 'libfastcv*' \)
emit "Adreno 630 graphics" \( -name '*adreno*' -o -name 'libgsl*' -o -name 'libllvm-glnext*' -o -name 'libCB.so' -o -name 'libOpenCL*' -o -name 'vulkan.*' \)
emit "Display / SDM" \( -name 'libsdm*' -o -name 'libqdMetaData*' -o -name 'libdisplay*' -o -name 'hw/gralloc.*' -o -name 'hw/hwcomposer.*' -o -name 'hw/memtrack.*' \)
emit "Sensors HAL" \( -name 'hw/sensors.*' -o -name 'libssc*' -o -name 'libsensor*' \)
emit "Audio" \( -name 'hw/audio.*' -o -name 'libaudio*' -o -name 'libacdb*' -o -name 'libadm*' \)
emit "Media / codecs" \( -name 'libOmx*' -o -name 'libc2d*' -o -name 'libmm-*' \)
emit "Wi-Fi / Bluetooth" \( -name '*wifi*' -o -name '*wcnss*' -o -name 'libbt-*' -o -name '*bluetooth*' \)
emit "DSP / adsprpc" \( -name 'libadsprpc*' -o -name 'libcdsprpc*' -o -path '*/rfsa/*' \)
emit "Firmware" -path '*/firmware/*'
emit "VR HAL + vendor HAL services" \( -path '*/bin/hw/*' -o -name 'hw/vr.*' \)
} > "$OUT"

# de-dup while preserving section structure
python3 - "$OUT" <<'PY'
import sys
p=sys.argv[1]
seen=set(); out=[]
for line in open(p):
    s=line.rstrip('\n')
    if s.startswith('#') or not s.strip():
        out.append(s); continue
    if s in seen: continue
    seen.add(s); out.append(s)
open(p,'w').write('\n'.join(out)+'\n')
print('unique blob entries: %d' % len(seen))
PY

echo "wrote $OUT"
grep -c '^vendor/' "$OUT"
